on:
  workflow_dispatch:

name: Build Services

jobs:
  pre_build:
    name: Pre build
    runs-on: ubuntu-20.04
    outputs:
      matrix: ${{ steps.format_input.outputs.matrix }}
      packages_to_build: ${{ steps.format_input.outputs.packages_to_build }}
    steps:
      - name: Format Input
        id: format_input
        run: |
          echo "matrix={\"packages_to_build\":[\"shalom,gal\"]}" >> $GITHUB_OUTPUT
          echo "packages_to_build=shalom,gal" >> $GITHUB_OUTPUT
  test_matrix:
    name: Test Matrix
    runs-on: ubuntu-20.04
    needs: pre_build
    strategy:
      matrix: ${{fromJson(needs.pre_build.outputs.packages_to_build)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set inputs
        id: set_inputs
        shell: bash
        run: |
          echo ${{ matrix }}
